//******************************************************************************
// <copyright file="license.md" company="RawCMS project  (https://github.com/arduosoft/RawCMS)">
// Copyright (c) 2019 RawCMS project  (https://github.com/arduosoft/RawCMS)
// RawCMS project is released under GPL3 terms, see LICENSE file on repository root at  https://github.com/arduosoft/RawCMS .
// </copyright>
// <author>Daniele Fontani, Emanuele Bucarelli, Francesco Mina'</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using CommandLine;

namespace RawCMS.Client.BLL.CommandLineParser
{
    [Verb("client", HelpText = "Set client configuration. Type client form more help.")]
    public class ClientOptions
    {
        //[Option('s', "syncronize", Required = false,  HelpText = "File path to synchronize the db.")]
        //public string SincronizationFile { get; set; }

        //[Option('r',"purge", Default = false, HelpText = "Remove data during syncronization. Only with syncronization (-s)")]
        //public bool RemoveData { get; set; }

        //[Option('d', "data", Required = false, HelpText = "file path contains data. using with create, update")]
        //public string DataFile { get; set; }
    }
}