//******************************************************************************
// <copyright file="license.md" company="RawCMS project  (https://github.com/arduosoft/RawCMS)">
// Copyright (c) 2019 RawCMS project  (https://github.com/arduosoft/RawCMS)
// RawCMS project is released under GPL3 terms, see LICENSE file on repository root at  https://github.com/arduosoft/RawCMS .
// </copyright>
// <author>Daniele Fontani, Emanuele Bucarelli, Francesco Mina'</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using Newtonsoft.Json.Linq;
using RawCMS.Library.Lambdas;
using System;

namespace RawCMS.Lambdas.Rest
{
    public class DummyRest : RestLambda
    {
        public override string Name => "DummyRest";

        public override string Description => "I'm a dumb dummy request";

        public override JObject Rest(JObject input)
        {
            JObject result = new JObject()
            {
                { "input",input},
                { "now",DateTime.Now},
            };

            return result;
        }
    }
}