//******************************************************************************
// <copyright file="license.md" company="RawCMS project  (https://github.com/arduosoft/RawCMS)">
// Copyright (c) 2019 RawCMS project  (https://github.com/arduosoft/RawCMS)
// RawCMS project is released under GPL3 terms, see LICENSE file on repository root at  https://github.com/arduosoft/RawCMS .
// </copyright>
// <author>Daniele Fontani, Emanuele Bucarelli, Francesco Mina'</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
namespace RawCMS.Library.Schema.FieldTypes
{
    public class FieldListType : FieldType
    {
        public override string TypeName => "fields-list";

        public override FieldGraphType GraphType => FieldGraphType.String;

        public FieldListType()
        {
            //
            OptionParameter.Add(new OptionParameter()
            {
                Name = "Collection",
                Type = "text",
                Description = "Collection name"
            });
        }
    }
}