//******************************************************************************
// <copyright file="license.md" company="RawCMS project  (https://github.com/arduosoft/RawCMS)">
// Copyright (c) 2019 RawCMS project  (https://github.com/arduosoft/RawCMS)
// RawCMS project is released under GPL3 terms, see LICENSE file on repository root at  https://github.com/arduosoft/RawCMS .
// </copyright>
// <author>Daniele Fontani, Emanuele Bucarelli, Francesco Mina'</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
namespace RawCMS.Library.Schema.FieldTypes
{
    public class NumberFieldType : FieldType
    {
        public override string TypeName => "number";

        public override FieldGraphType GraphType => FieldGraphType.Decimal;

        public NumberFieldType()
        {
            OptionParameter.Add(new OptionParameter()
            {
                Name = "max",
                Type = "number"
            });

            OptionParameter.Add(new OptionParameter()
            {
                Name = "min",
                Type = "number"
            });
        }
    }
}