//******************************************************************************
// <copyright file="license.md" company="RawCMS project  (https://github.com/arduosoft/RawCMS)">
// Copyright (c) 2019 RawCMS project  (https://github.com/arduosoft/RawCMS)
// RawCMS project is released under GPL3 terms, see LICENSE file on repository root at  https://github.com/arduosoft/RawCMS .
// </copyright>
// <author>Daniele Fontani, Emanuele Bucarelli, Francesco Mina</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using System;

namespace RawCMS.Plugins.LogCollecting.Model
{
    public class LogStatistic
    {
        public string ApplicationId { get; set; }
        public string ApplicationName { get; set; }
        public int Count { get; set; }
        public DateTime Time { get; set; }
    }
}