//******************************************************************************
// <copyright file="license.md" company="RawCMS project  (https://github.com/arduosoft/RawCMS)">
// Copyright (c) 2019 RawCMS project  (https://github.com/arduosoft/RawCMS)
// RawCMS project is released under GPL3 terms, see LICENSE file on repository root at  https://github.com/arduosoft/RawCMS .
// </copyright>
// <author>Daniele Fontani, Emanuele Bucarelli, Francesco Mina</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using Microsoft.Extensions.Logging;
using Newtonsoft.Json.Linq;
using RawCMS.Library.BackgroundJobs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RawCMS.Lambdas.Background
{
    public class PingJob : BackgroundJobInstance
    {
        public override string CronExpression => Hangfire.Cron.Minutely();

        public override string Name => "Ping Every minute";

        public override string Description => "Ping Every minute";

        protected ILogger logger;

        public PingJob(ILogger logger)
        {
            this.logger = logger;
        }

        public override void Execute(JObject data)
        {
            this.logger.LogInformation($"Job triggered, with data {data}");
        }
    }
}