//******************************************************************************
// <copyright file="license.md" company="RawCMS project  (https://github.com/arduosoft/RawCMS)">
// Copyright (c) 2019 RawCMS project  (https://github.com/arduosoft/RawCMS)
// RawCMS project is released under GPL3 terms, see LICENSE file on repository root at  https://github.com/arduosoft/RawCMS .
// </copyright>
// <author>Daniele Fontani, Emanuele Bucarelli, Francesco Mina'</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using System.Collections.Generic;

namespace RawCMS.Library.DataModel
{
    public class SortOption
    {
        public string Field { get; set; }
        public bool Ascending { get; set; }
    }

    public class DataQuery
    {
        public string RawQuery { get; set; }
        public int PageNumber { get; set; }
        public int PageSize { get; set; }
        public List<SortOption> Sort { get; set; }
        public List<string> Expando { get; set; }
    }
}