//******************************************************************************
// <copyright file="license.md" company="RawCMS project  (https://github.com/arduosoft/RawCMS)">
// Copyright (c) 2019 RawCMS project  (https://github.com/arduosoft/RawCMS)
// RawCMS project is released under GPL3 terms, see LICENSE file on repository root at  https://github.com/arduosoft/RawCMS .
// </copyright>
// <author>Daniele Fontani, Emanuele Bucarelli, Francesco Mina'</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using Jint;
using Newtonsoft.Json.Linq;
using RawCMS.Library.Core;
using RawCMS.Library.Core.Enum;
using RawCMS.Library.JavascriptClient;
using RawCMS.Library.Service;
using System.Collections.Generic;

namespace RawCMS.Library.Lambdas
{
    public abstract class JsDispatcher : DataProcessLambda 
    {
        public override string Name => "JsDispatcher";

        public override string Description => "JsDispatcher";

        protected readonly EntityService entityService;

        public JsDispatcher(EntityService entityService)
        {
            this.entityService = entityService;
        }

        public override void ExecuteInternal(string collection, ref JObject item, ref Dictionary<string, object> dataContext)
        {
            var settings = this.entityService.GetByName(collection);
            if (settings != null)
            {
                if (!string.IsNullOrEmpty(settings.PresaveScript))
                {
                    Dictionary<string, object> input = item.ToObject<Dictionary<string, object>>();

                    Engine engine = new Engine((x) => { x.AllowClr(typeof(JavascriptRestClient).Assembly); x.AllowClr(typeof(JavascriptRestClientRequest).Assembly); });
                    engine.SetValue("RAWCMSRestClient", Jint.Runtime.Interop.TypeReference.CreateTypeReference(engine, typeof(JavascriptRestClient)));
                    engine.SetValue("RAWCMSRestClientRequest", Jint.Runtime.Interop.TypeReference.CreateTypeReference(engine, typeof(JavascriptRestClientRequest)));
                    engine.SetValue("item", input);
                    engine.Execute(settings.PresaveScript);
                    item = JObject.FromObject(input);
                }
            }
        }
    }

    public class PreSaveEvent : JsDispatcher
    {
        public override PipelineStage Stage => PipelineStage.PreOperation;

        public override DataOperation Operation => DataOperation.Write;

        public override string Name => "PreSaveEvent";

        public override string Description => "PreSaveEvent";

        protected readonly static EntityService entityService;

        public PreSaveEvent(): base(entityService)
        {
            
        }


        public override void ExecuteInternal(string collection, ref JObject item, ref Dictionary<string, object> dataContext)
        {
            
        }
    }

    public class PostSaveEvent : JsDispatcher
    {
        public override PipelineStage Stage => PipelineStage.PreOperation;

        public override DataOperation Operation => DataOperation.Write;

        public override string Name => "PreSaveEvent";

        public override string Description => "PreSaveEvent";

        protected readonly static EntityService entityService;

        public PostSaveEvent() : base(entityService)
        {

        }


        public override void ExecuteInternal(string collection, ref JObject item, ref Dictionary<string, object> dataContext)
        {

        }
    }

    public class PreDeleteEvent : JsDispatcher
    {
        public override PipelineStage Stage => PipelineStage.PreOperation;

        public override DataOperation Operation => DataOperation.Write;

        public override string Name => "PreSaveEvent";

        public override string Description => "PreSaveEvent";

        protected readonly static EntityService entityService;

        public PreDeleteEvent() : base(entityService)
        {

        }


        public override void ExecuteInternal(string collection, ref JObject item, ref Dictionary<string, object> dataContext)
        {

        }
    }

    public class PostDeleteEvent : JsDispatcher
    {
        public override PipelineStage Stage => PipelineStage.PreOperation;

        public override DataOperation Operation => DataOperation.Write;

        public override string Name => "PreSaveEvent";

        public override string Description => "PreSaveEvent";

        protected readonly static EntityService entityService;

        public PostDeleteEvent() : base(entityService)
        {

        }


        public override void ExecuteInternal(string collection, ref JObject item, ref Dictionary<string, object> dataContext)
        {

        }
    }


}