//******************************************************************************
// <copyright file="license.md" company="RawCMS project  (https://github.com/arduosoft/RawCMS)">
// Copyright (c) 2019 RawCMS project  (https://github.com/arduosoft/RawCMS)
// RawCMS project is released under GPL3 terms, see LICENSE file on repository root at  https://github.com/arduosoft/RawCMS .
// </copyright>
// <author>Daniele Fontani, Emanuele Bucarelli, Francesco Mina</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using RawCMS.Library.UI;
using System.Collections.Generic;

namespace RawCMS.Plugins.Core.Model
{
    public class UIResult
    {
        public Api api { get; set; }
        public Login login { get; set; }

        public List<UIMetadata> metadata { get; set; }
    }

    public class Api
    {
        public string baseUrl { get; set; }
    }

    public class Login
    {
        public string grant_type { get; set; }
        public string scope { get; set; }
        public string client_id { get; set; }
        public string client_secret { get; set; }
    }
}