FROM mcr.microsoft.com/dotnet/core/runtime:3.1.2-alpine AS base
WORKDIR /app


FROM mcr.microsoft.com/dotnet/core/sdk:3.1.200-alpine AS build
WORKDIR /src
COPY ./docker/config/api/buildscript.sh ./build.sh
COPY . .

RUN chmod +x ./build.unix.sh && build.unix.sh

FROM base AS final
WORKDIR /app
COPY --from=build /dist .
ENTRYPOINT ["dotnet", "RawCMS.dll"]
