FROM mcr.microsoft.com/dotnet/core/runtime:latest AS base
WORKDIR /app


FROM mcr.microsoft.com/dotnet/core/sdk:latest AS build
WORKDIR /src
COPY ./docker/config/api/buildscript.sh ./build.unix.sh
COPY . .

RUN chmod +x ./build.unix.sh && bash /src/build.unix.sh

FROM base AS final
WORKDIR /app
COPY --from=build /dist .
ENTRYPOINT ["dotnet", "RawCMS.dll"]
