//******************************************************************************
// <copyright file="license.md" company="RawCMS project  (https://github.com/arduosoft/RawCMS)">
// Copyright (c) 2019 RawCMS project  (https://github.com/arduosoft/RawCMS)
// RawCMS project is released under GPL3 terms, see LICENSE file on repository root at  https://github.com/arduosoft/RawCMS .
// </copyright>
// <author>Daniele Fontani, Emanuele Bucarelli, Francesco Mina'</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using Microsoft.AspNetCore.Authorization;

namespace RawCMS.Library.Core.Attributes
{
    public class RawAuthenticationAttribute : AuthorizeAttribute
    {
        //TODO: a che serve?
        public RawAuthenticationAttribute()
        {
            AuthenticationSchemes = "Bearer";
        }
    }
}