//******************************************************************************
// <copyright file="license.md" company="RawCMS project  (https://github.com/arduosoft/RawCMS)">
// Copyright (c) 2019 RawCMS project  (https://github.com/arduosoft/RawCMS)
// RawCMS project is released under GPL3 terms, see LICENSE file on repository root at  https://github.com/arduosoft/RawCMS .
// </copyright>
// <author>Daniele Fontani, Emanuele Bucarelli, Francesco Min�</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using NLog.Web;
using RawCMS.Library.Core.Helpers;

namespace RawCMS
{
    public class Program
    {
        public static void Main(string[] args)
        {
            
            try
            {
                Debug.WriteLine("Starting MAIN");
                Run();

            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);                
                throw;
            }
            finally
            {
                // Ensure to flush and stop internal timers/threads before application-exit (Avoid segmentation fault on Linux)
                NLog.LogManager.Shutdown();
            }
        }

        

        private static void Run()
        {
            IWebHost host = new WebHostBuilder()
                            .UseNLog()
                            .UseKestrel()
                            .UseContentRoot(Directory.GetCurrentDirectory())
                            .UseIISIntegration()
                            .UseStartup<Startup>()
                            .UseSetting("detailedErrors", "true")
                            .ConfigureLogging(logger =>
                            {

                                logger.ClearProviders();
                                logger.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace);
                            })
                            .UseNLog()
                            .Build();

            host.Run();
        }
    }
}