//******************************************************************************
// <copyright file="license.md" company="RawCMS project  (https://github.com/arduosoft/RawCMS)">
// Copyright (c) 2019 RawCMS project  (https://github.com/arduosoft/RawCMS)
// RawCMS project is released under GPL3 terms, see LICENSE file on repository root at  https://github.com/arduosoft/RawCMS .
// </copyright>
// <author>Daniele Fontani, Emanuele Bucarelli, Francesco Mina'</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using Newtonsoft.Json.Linq;
using System.Collections.Generic;

namespace RawCMS.Library.Core
{
    public enum SavePipelineStage
    {
        PreSave = 0x0,
        PostSave = 0x1,
    }

    public enum DataOperation
    {
        Read,
        Write,
        Delete
    }

    public abstract class DataProcessLambda : Lambda
    {
        public abstract SavePipelineStage Stage { get; }
        public abstract DataOperation Operation { get; }

        public abstract void Execute(string collection, ref JObject item, ref Dictionary<string, object> dataContext);
    }

    public abstract class PostSaveLambda : DataProcessLambda
    {
        public override SavePipelineStage Stage => SavePipelineStage.PostSave;
        public override DataOperation Operation => DataOperation.Write;
    }

    public abstract class PreSaveLambda : DataProcessLambda
    {
        public override SavePipelineStage Stage => SavePipelineStage.PreSave;
        public override DataOperation Operation => DataOperation.Write;
    }

    public abstract class PostDeleteLambda : DataProcessLambda
    {
        public override SavePipelineStage Stage => SavePipelineStage.PostSave;
        public override DataOperation Operation => DataOperation.Delete;
    }

    public abstract class PreDeleteLambda : DataProcessLambda
    {
        public override SavePipelineStage Stage => SavePipelineStage.PreSave;
        public override DataOperation Operation => DataOperation.Delete;
    }
}