//******************************************************************************
// <copyright file="license.md" company="RawCMS project  (https://github.com/arduosoft/RawCMS)">
// Copyright (c) 2019 RawCMS project  (https://github.com/arduosoft/RawCMS)
// RawCMS project is released under GPL3 terms, see LICENSE file on repository root at  https://github.com/arduosoft/RawCMS .
// </copyright>
// <author>Daniele Fontani, Emanuele Bucarelli, Francesco Mina'</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
namespace RawCMS.Plugins.Core.Configuration
{
    public enum OAuthMode
    {
        JWT,
        Introspection
    }

    public class ExternalProvider
    {
        public OAuthMode Mode { get; set; }
        public string SchemaName { get; set; }
        public string Authority { get; set; }
        public string Audience { get; set; }
        public string UserInfoEndpoint { get; set; }
        public string RoleClaimType { get; set; }
    }
}