//******************************************************************************
// <copyright file="license.md" company="RawCMS project  (https://github.com/arduosoft/RawCMS)">
// Copyright (c) 2019 RawCMS project  (https://github.com/arduosoft/RawCMS)
// RawCMS project is released under GPL3 terms, see LICENSE file on repository root at  https://github.com/arduosoft/RawCMS .
// </copyright>
// <author>Daniele Fontani, Emanuele Bucarelli, Francesco Mina</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using Microsoft.AspNetCore.Mvc;
using RawCMS.Plugins.LogCollecting.Model;
using RawCMS.Plugins.LogCollecting.Services;
using System.Collections.Generic;

namespace RawCMS.Plugins.LogCollecting.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class LogStaticsController : ControllerBase
    {
        protected LogService service;

        public LogStaticsController(LogService logService)
        {
            service = logService;
        }

        [HttpGet]
        public List<LogStatistic> Get()
        {
            return service.GetStatistic();
        }

        [HttpGet]
        [Route("applicationId")]
        public List<LogStatistic> Get(string applicationId)
        {
            return service.GetStatistic();
        }
    }
}