//******************************************************************************
// <copyright file="license.md" company="RawCMS project  (https://github.com/arduosoft/RawCMS)">
// Copyright (c) 2019 RawCMS project  (https://github.com/arduosoft/RawCMS)
// RawCMS project is released under GPL3 terms, see LICENSE file on repository root at  https://github.com/arduosoft/RawCMS .
// </copyright>
// <author>Daniele Fontani, Emanuele Bucarelli, Francesco Min�</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using Newtonsoft.Json.Linq;
using RawCMS.Library.Core;
using System;

namespace RawCMS.Plugins.Core.Lambdas
{
    public class UserInfoLambda : RestLambda
    {
        public override string Name => "UserInfo";

        public override string Description => throw new NotImplementedException();

        public override JObject Rest(JObject input)
        {
            JObject jj = new JObject
            {
                ["IsAuthenticated"] = Request.User.Identity.IsAuthenticated
            };
            foreach (System.Security.Claims.Claim claim in Request.User.Claims)
            {
                jj[claim.Type] = claim.Value;
            }
            return jj;
        }
    }
}