//******************************************************************************
// <copyright file="license.md" company="RawCMS project  (https://github.com/arduosoft/RawCMS)">
// Copyright (c) 2019 RawCMS project  (https://github.com/arduosoft/RawCMS)
// RawCMS project is released under GPL3 terms, see LICENSE file on repository root at  https://github.com/arduosoft/RawCMS .
// </copyright>
// <author>Daniele Fontani, Emanuele Bucarelli, Francesco Mina'</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using IdentityServer4.Services;
using Microsoft.Extensions.DependencyInjection;
using RawCMS.Plugins.Core.Stores;

namespace RawCMS.Plugins.Core.Extensions
{
    public static class IdentityServerExtensions
    {
        public static IIdentityServerBuilder AddProfileServiceCustom(this IIdentityServerBuilder builder)
        {
            builder.Services.AddTransient<IProfileService, RawUserStore>();

            return builder;
        }
    }
}