//******************************************************************************
// <copyright file="license.md" company="RawCMS project  (https://github.com/arduosoft/RawCMS)">
// Copyright (c) 2019 RawCMS project  (https://github.com/arduosoft/RawCMS)
// RawCMS project is released under GPL3 terms, see LICENSE file on repository root at  https://github.com/arduosoft/RawCMS .
// </copyright>
// <author>Daniele Fontani, Emanuele Bucarelli, Francesco Mina'</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using RawCMS.Library.Core.Attributes;
using System;

namespace RawCMS.Plugins.Core.Controllers.Controllers.admin
{
    [Authorize(AuthenticationSchemes = "Bearer")]
    [Authorize(Roles = "Admin", AuthenticationSchemes = "Bearer,ApiKey")]
    [Route("system/[controller]")]
    public class ConfigController : Controller
    {
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IConfigurationRoot _configuration;
        public ConfigController(IHostingEnvironment hostingEnvironment, IConfigurationRoot configuration)
        {
            _hostingEnvironment = hostingEnvironment;
            _configuration = configuration;
        }

        [HttpGet("reload")]
        public ActionResult Reload()
        {
            try
            {
                var projectRootPath = _hostingEnvironment.ContentRootPath;
                var reloadFile = _configuration["ReloadConfigPath"];
                var reloadFilePath = System.IO.Path.Combine(projectRootPath, reloadFile);
                System.IO.File.WriteAllText(reloadFilePath, DateTime.Now.ToString());
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.ToString());
            }
            return Ok();
        }
    }
}