//******************************************************************************
// <copyright file="license.md" company="RawCMS project  (https://github.com/arduosoft/RawCMS)">
// Copyright (c) 2019 RawCMS project  (https://github.com/arduosoft/RawCMS)
// RawCMS project is released under GPL3 terms, see LICENSE file on repository root at  https://github.com/arduosoft/RawCMS .
// </copyright>
// <author>Daniele Fontani, Emanuele Bucarelli, Francesco Mina</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using Newtonsoft.Json.Linq;
using RawCMS.Library.Lambdas;
using RawCMS.Library.Schema;
using System;
using System.Collections.Generic;

namespace RawCMS.Plugins.Core.Lambdas.Applications
{
    public class ApplicationDeleteForbidden : PreDeleteLambda
    {
        public override string Name => "ApplicationDeleteForbidden";

        public override string Description => "application collection cannot be deleted";

        public override void Execute(string collection, ref JObject item, ref Dictionary<string, object> dataContext)
        {
            if (collection == "_schema")
            {
                var schema = item.ToObject<CollectionSchema>();
                if (schema.CollectionName == "application")
                {
                    throw new Exception("Unable to delete application ");
                }
            }
        }
    }
}