//******************************************************************************
// <copyright file="license.md" company="RawCMS project  (https://github.com/arduosoft/RawCMS)">
// Copyright (c) 2019 RawCMS project  (https://github.com/arduosoft/RawCMS)
// RawCMS project is released under GPL3 terms, see LICENSE file on repository root at  https://github.com/arduosoft/RawCMS .
// </copyright>
// <author>Daniele Fontani, Emanuele Bucarelli, Francesco Min�</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
using GraphQL.Types;
using Newtonsoft.Json.Linq;
using RawCMS.Library.Service.Contracts;
using RawCMS.Plugins.GraphQL.Types;

namespace RawCMS.Plugins.GraphQL.Classes
{
    public class GraphQLQuery : ObjectGraphType<JObject>
    {
        public GraphQLQuery(ICollectionMetadata collectionMetadata, GraphQLService graphQLService)
        {
            Name = "Query";
            foreach (Library.Schema.CollectionSchema metaColl in collectionMetadata.GetCollectionSchemas())
            {
                CollectionType type = new CollectionType(metaColl);
                ListGraphType listType = new ListGraphType(type);
                AddField(new FieldType
                {
                    Name = metaColl.CollectionName,
                    Type = listType.GetType(),
                    ResolvedType = listType,
                    Resolver = new JObjectFieldResolver(graphQLService),
                    Arguments = new QueryArguments(
                        type.TableArgs
                    )
                });
            }
        }
    }
}