//******************************************************************************
// <copyright file="license.md" company="RawCMS project  (https://github.com/arduosoft/RawCMS)">
// Copyright (c) 2019 RawCMS project  (https://github.com/arduosoft/RawCMS)
// RawCMS project is released under GPL3 terms, see LICENSE file on repository root at  https://github.com/arduosoft/RawCMS .
// </copyright>
// <author>Daniele Fontani, Emanuele Bucarelli, Francesco Mina'</author>
// <autogenerated>true</autogenerated>
//******************************************************************************
namespace RawCMS.Library.Schema
{
    public enum FieldGraphType
    {
        Int,
        Long,
        BigInt,
        Float,
        Short,
        Decimal,
        String,
        Boolean,
        Id,
        Date,
        DateTimeOffset,
        TimeSpanSeconds,
        Relation,
        Byte,
        SByte
    }

    //        Allowed GraphType
    //        [typeof(int)] = typeof(IntGraphType),
    //        [typeof(long)] = typeof(LongGraphType),
    //        [typeof(BigInteger)] = typeof(BigIntGraphType),
    //        [typeof(double)] = typeof(FloatGraphType),
    //        [typeof(float)] = typeof(FloatGraphType),
    //        [typeof(decimal)] = typeof(DecimalGraphType),
    //        [typeof(string)] = typeof(StringGraphType),
    //        [typeof(bool)] = typeof(BooleanGraphType),
    //        [typeof(DateTime)] = typeof(DateGraphType),
    //        [typeof(DateTimeOffset)] = typeof(DateTimeOffsetGraphType),
    //        [typeof(TimeSpan)] = typeof(TimeSpanSecondsGraphType),
    //        [typeof(Guid)] = typeof(IdGraphType),
    //        [typeof(short)] = typeof(ShortGraphType),
    //        [typeof(ushort)] = typeof(UShortGraphType),
    //        [typeof(ulong)] = typeof(ULongGraphType),
    //        [typeof(uint)] = typeof(UIntGraphType),
    //        [typeof(byte)] = typeof(ByteGraphType),
    //        [typeof(sbyte)] = typeof(SByteGraphType),
}